# Tasan et.al. 2015 Acta Materalia
# Tasan et.al. 2015 International Journal of Plasticity
# Diehl et.al. 2015 Meccanica
Ferrite:
  lattice: cI
  mechanical:
    elastic: {C_11: 233.3e9, C_12: 135.5e9, C_44: 118.0e9, type: Hooke}
    plastic:
      N_sl: [12, 12]
      a_sl: 2.0
      dot_gamma_0_sl: 0.001
      h_0_sl_sl: 1000.0e6
      h_sl_sl: [1, 1.4, 1, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4]
      n_sl: 20
      type: phenopowerlaw
      xi_0_sl: [95.e6, 96.e6]
      xi_inf_sl: [222.e6, 412.7e6]
