# M. Levy, Handbook of Elastic Properties of Solids, Liquids, and Gases (2001)
# C. Zambaldi, "Orientation informed nanoindentation of a-titanium: Indentation pileup in hexagonal metals deforming by prismatic slip", J. Mater. Res., Vol. 27, No. 1, Jan 14, 2012
# Better use values from L. Wang, Z. Zheng, H. Phukan, P. Kenesei, J.-S. Park, J. Lind, R.M. Suter, T.R. Bieler, Direct measurement of critical resolved shear stress of prismatic and basal slip in polycrystalline Ti using high energy X-ray diffraction microscopy, Acta Mater 2017
cpTi:
  lattice: hP
  c/a: 1.587
  mechanical:
    output: [F, P, F_e, F_p, L_p, O]
    elastic: {C_11: 160.0e9, C_12: 90.0e9, C_13: 66.0e9, C_33: 181.7e9, C_44: 46.5e9, type: Hooke}
    plastic:
      N_sl: [3, 3, 0, 6, 12]
      a_sl: 2.0
      dot_gamma_0_sl: 0.001
      h_0_sl_sl: 200e6
      h_sl_sl: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
      n_sl: 20
      output: [gamma_sl]
      type: phenopowerlaw
      xi_0_sl: [0.15e9, 0.09e9, 0, 0.20e9, 0.25e9]
      xi_inf_sl: [0.24e9, 0.5e9, 0, 0.6e9, 0.8e9]
