Aluminum:
  lattice: cF
  mechanical:
    output: [F, P, F_e, F_p, L_p, O]
    elastic: {C_11: 106.75e9, C_12: 60.41e9, C_44: 28.34e9, type: Hooke}
    plastic:
      N_sl: [12]
      a_sl: 2.25
      dot_gamma_0_sl: 0.001
      h_0_sl_sl: 75e6
      h_sl_sl: [1, 1, 1.4, 1.4, 1.4, 1.4, 1.4]
      n_sl: 20
      output: [xi_sl, gamma_sl]
      type: phenopowerlaw
      xi_0_sl: [31e6]
      xi_inf_sl: [63e6]
