# Tasan et.al. 2015 Acta Materalia
# Tasan et.al. 2015 International Journal of Plasticity
# Diehl et.al. 2015 Meccanica
Martensite:
  lattice: cI
  mechanical:
    elastic: {C_11: 417.4e9, C_12: 242.4e9, C_44: 211.1e9, type: Hooke}
    plastic:
      N_sl: [12, 12]
      a_sl: 2.0
      dot_gamma_0_sl: 0.001
      h_0_sl_sl: 563.0e9
      h_sl_sl: [1, 1.4, 1, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4]
      n_sl: 20
      type: phenopowerlaw
      xi_0_sl: [405.8e6, 456.7e6]
      xi_inf_sl: [872.9e6, 971.2e6]
