Tungsten:
  lattice: cI
  mechanical:
    elastic: {type: Hooke, C_11: 523.0e9, C_12: 202.0e9, C_44: 161.0e9} # Marinica et al. Journal of Physics: Condensed Matter(2013)
    plastic:
      type: dislotwin
      D: 2.0e-5              # Average grain size / m
      N_sl: [12]
      b_sl: [2.72e-10]       # Burgers vector length of slip families / m
      rho_mob_0: [1.0e12]
      rho_dip_0: [1.0]
      v_0: [1.0e4]           # Initial glide velocity / m/s
      Q_s: [2.725e-19]       # Activation energy for dislocation glide / J
      p_sl: [0.78]           # p-exponent in glide velocity
      q_sl: [1.58]           # q-exponent in glide velocity
      tau_0: [1.5e8]         # solid solution strength / Pa
      i_sl: [10.0]           # Adj. parameter controlling dislocation mean free path
      D_0: 4.0e-5            # Vacancy diffusion prefactor / m^2/s
      D_a: 1.0               # minimum dipole distance / b
      Q_cl: 4.5e-19          # Activation energy for climb / J
      h_sl_sl: [1, 1.4, 1, 1.4, 1.4, 1.4, 1.4]
