FreeSurface:
  lattice: cI
  mechanical:
    output: [F, P, F_e, F_p, L_p]
    elastic: {type: Hooke, C_11: 1e8, C_12: 1e6, C_44: 4.95e7}
    plastic:
      type: isotropic
      output: [xi]
      xi_0: 0.3e6
      xi_inf: 0.6e6
      dot_gamma_0: 0.001
      n: 5
      M: 3
      h_0: 1e6
      a: 2
      dilatation: True
